[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "typhoon-asr"
version = "0.1.0"
authors = [
  { name="Warit Sirichotedumrong", email="warit@scb10x.com" },
]
description = "A user-friendly package for Thai speech recognition using the Typhoon ASR model."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "absl-py==2.3.1",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "alembic==1.16.4",
    "antlr4-python3-runtime==4.9.3",
    "appnope==0.1.4",
    "asteroid-filterbanks==0.4.0",
    "asttokens==3.0.0",
    "async-timeout==5.0.1",
    "attrs==25.3.0",
    "audioread==3.0.1",
    "backcall==0.2.0",
    "beautifulsoup4==4.13.5",
    "bleach==6.2.0",
    "braceexpand==0.1.7",
    "certifi==2025.8.3",
    "cffi==1.17.1",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "colorlog==6.9.0",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "cytoolz==1.0.1",
    "datasets==4.0.0",
    "decorator==5.2.1",
    "defusedxml==0.7.1",
    "dill==0.3.8",
    "docopt==0.6.2",
    "editdistance==0.8.1",
    "einops==0.8.1",
    "evaluate==0.4.5",
    "exceptiongroup==1.3.0",
    "executing==2.2.0",
    "fastjsonschema==2.21.2",
    "filelock==3.19.1",
    "fonttools==4.59.1",
    "frozenlist==1.7.0",
    "fsspec==2024.12.0",
    "grpcio==1.74.0",
    "hf-xet==1.1.8",
    "huggingface-hub==0.34.4",
    "hydra-core==1.3.2",
    "HyperPyYAML==1.2.2",
    "idna==3.10",
    "intervaltree==3.1.0",
    "ipython==8.12.3",
    "jedi==0.19.2",
    "Jinja2==3.1.6",
    "jiwer==4.0.0",
    "joblib==1.5.1",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.4.1",
    "julius==0.2.7",
    "jupyter_client==8.6.3",
    "jupyter_core==5.8.1",
    "jupyterlab_pygments==0.3.0",
    "kiwisolver==1.4.9",
    "lazy_loader==0.4",
    "lhotse==1.30.3",
    "librosa==0.11.0",
    "lightning==2.5.3",
    "lightning-utilities==0.15.2",
    "lilcom==1.8.1",
    "llvmlite==0.44.0",
    "Mako==1.3.10",
    "Markdown==3.8.2",
    "markdown-it-py==4.0.0",
    "MarkupSafe==3.0.2",
    "matplotlib==3.10.5",
    "matplotlib-inline==0.1.7",
    "mdurl==0.1.2",
    "mistune==3.1.3",
    "mpmath==1.3.0",
    "msgpack==1.1.1",
    "multidict==6.6.4",
    "multiprocess==0.70.16",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "nbformat==5.10.4",
    "nemo-toolkit==2.4.0",
    "networkx==3.4.2",
    "numba==0.61.2",
    "numpy==2.2.6",
    "omegaconf==2.3.0",
    "onnx==1.18.0",
    "optuna==4.5.0",
    "packaging==25.0",
    "pandas==2.3.2",
    "pandocfilters==1.5.1",
    "parso==0.8.5",
    "pexpect==4.9.0",
    "pickleshare==0.7.5",
    "pillow==11.3.0",
    "pipreqs==0.5.0",
    "platformdirs==4.3.8",
    "pooch==1.8.2",
    "primePy==1.3",
    "prompt_toolkit==3.0.51",
    "propcache==0.3.2",
    "protobuf==5.29.5",
    "ptyprocess==0.7.0",
    "pure_eval==0.2.3",
    "pyannote.audio==3.3.2",
    "pyannote.core==5.0.0",
    "pyannote.database==5.1.3",
    "pyannote.metrics==3.2.1",
    "pyannote.pipeline==3.0.1",
    "pyarrow==21.0.0",
    "pycparser==2.22",
    "Pygments==2.19.2",
    "pyparsing==3.2.3",
    "python-dateutil==2.9.0.post0",
    "pytorch-lightning==2.5.3",
    "pytorch-metric-learning==2.9.0",
    "pytz==2025.2",
    "PyYAML==6.0.2",
    "pyzmq==27.0.2",
    "RapidFuzz==3.13.0",
    "referencing==0.36.2",
    "regex==2025.7.34",
    "requests==2.32.5",
    "rich==14.1.0",
    "rpds-py==0.27.0",
    "ruamel.yaml==0.18.15",
    "ruamel.yaml.clib==0.2.12",
    "safetensors==0.6.2",
    "scikit-learn==1.7.1",
    "scipy==1.15.3",
    "semver==3.0.4",
    "sentencepiece==0.2.1",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sortedcontainers==2.4.0",
    "soundfile==0.13.1",
    "soupsieve==2.7",
    "soxr==0.5.0.post1",
    "speechbrain==1.0.3",
    "SQLAlchemy==2.0.43",
    "stack-data==0.6.3",
    "sympy==1.14.0",
    "tabulate==0.9.0",
    "tensorboard==2.20.0",
    "tensorboard-data-server==0.7.2",
    "tensorboardX==2.6.4",
    "text-unidecode==1.3",
    "threadpoolctl==3.6.0",
    "tinycss2==1.4.0",
    "tokenizers==0.21.4",
    "tomli==2.2.1",
    "toolz==1.0.0",
    "torch==2.8.0",
    "torch-audiomentations==0.12.0",
    "torch_pitch_shift==1.2.5",
    "torchaudio==2.8.0",
    "torchmetrics==1.8.1",
    "torchvision==0.23.0",
    "tornado==6.5.2",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "transformers==4.55.4",
    "typer==0.16.1",
    "typing_extensions==4.14.1",
    "tzdata==2025.2",
    "urllib3==2.5.0",
    "wcwidth==0.2.13",
    "webdataset==1.0.2",
    "webencodings==0.5.1",
    "Werkzeug==3.1.3",
    "wget==3.2",
    "wrapt==1.17.3",
    "xxhash==3.5.0",
    "yarg==0.1.9",
    "yarl==1.20.1",
]

[project.urls]
"Homepage" = "https://github.com/scb10x/typhoon-asr"
"Bug Tracker" = "https://github.com/scb10x/typhoon-asr/issues"

[project.scripts]
typhoon-asr = "typhoon_asr.cli:main"